language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-user a1super/udagram-api-user:v8
  - docker tag udagram-api-feed a1super/udagram-api-feed:v8
  - docker tag udagram-frontend a1super/udagram-frontend:v8
  - docker tag reverseproxy a1super/reverseproxy:v8

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push a1super/udagram-api-user:v8
  - docker push a1super/udagram-api-feed:v8
  - docker push a1super/udagram-frontend:v8
  - docker push a1super/reverseproxy:v8
