apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: udagram-api-user
          image: a1super/udagram-api-user
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
              name: env-configmap
            - secretRef:
              name: env-secret
